### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by robertswiecki** [google/honggfuzz#139]
Hi all!

According to the _quite random_ release numbering - from https://github.com/google/honggfuzz/releases - the next version will be __1.0__ :). Hoorraaay!

I'd like to release it somewhere next week, and by that time to confirm that it compiles and works under various platforms w/o bigger problems. If you'd like to help me, I'll be glad for testing the master branch and letting me know if it works (or doesn't under any reasonable platform you can test it with).

I'd like to have it tested, at a minimum, with the following configs:

----
**Linux (various distros):**
- [x] i386:
  - [x] Unknown distro: Compiles, Works
- [x] x86-64:
  - [x] GCC: Ubuntu 17.04: Compiles, Works (sancov, bts/ipt, finstrument-functions, persistent mode): 
  - [x] Clang 4.0/5.0 Ubuntu 17.04: Compiles, Works
  - [x] GCC: Fedora 25: Compiles, Works
- [x] arm: Ubuntu 16.04
- [x] arm64: Ubuntu 16.04
- [ ] ppc32:
- [x] ppc64: Ubuntu 16.04
- [ ] mips:
- [ ] mips64:

**Android:**
- [x] armeabi:
- [x] armeabi-v7a:
- [x] x86
- [x] x86_64
- [x] arm64-v8a

**CygWin:**
- [x] x86-64
  - [-] Clang - Will not compile, one of the system headers is using __blocks as a argument's name
  - [x] GCC - Compiles, Works with basic cases (no instrumentation)

**FreeBSD:**
- [x] x86-64
  - [x] Clang
  - [x] GCC

**MacOS:**
- [x] Mac OS Sierra 10.12.5
- [x] macOS El Capitan 10.11.6 
----

Mentioning a couple of people who worked on the code in the past in case they would like to help me with quick testing :)

@anestisb @tl0gic @felixgr @riusksk @Manouchehri @dyjakan

**Comment by dyjakan** [comment]
Awesome. I will test it over the weekend on platforms that I have available to me (Linux and macOS). ✌️

**Comment by anestisb** [comment]
Great news. I'll test all the Android targets against the latest stable NDK & API level. Hopefully it will be done by Friday.

**Comment by riusksk** [comment]
Nice, I will test on Linux , windows, android and mac

**Comment by riusksk** [comment]
cygwin win10 x64 gcc compile error:

> libhfuzz/instrument.c:1:0: 错误：-fPIC 在目标机上被忽略 (所有代码都是与位置无关的) [-Werror]
> #include <unistd.h>
> ^
>cc1: 错误：unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
>cc1: 错误：unrecognized command line option ‘-Wno-initializer-overrides’ [-Werror]
>cc1：所有的警告都被当作是错误
> make: *** [Makefile:245：libhfuzz/instrument.o] 错误 1

you can del `-Werror` or -fPIC  in Makefile for windows

**Comment by anestisb** [comment]
Tested all Android targets using a macOS host for the cross-compilation builds and the latest Android NDK r14b. Target devices + emulator images where API 23, API 24 & API 25.Tests have included the https://github.com/google/honggfuzz/pull/140 PR.

I still haven't updated libunwind to latest upstream commit since there are quite a few patches that need backporting + testing. Ideally I'll aim for the near future to switch to AOSP libunwind so that we can benefit from the maintenance effort already taking place from stable Android.

| **Platform**            | **Compilation: clang + gcc (main, deps, libhfuzz)** | **Running: clang + gcc**         |
| :---------------------- | :--------------------------------------- | :-------------------------------- |
| **Android arm64-v8a**   | ✓                                        | ✓                                 |
| **Android armeabi-v7a** | ✓                                        | ✓ (tested on arm64 device too)    |
| **Android armeabi**     | ✓                                        | ✓ (tested on arm64 device too)    |
| **Android x86**         | ✓                                        | ✓                                 |
| **Android x86_64**      | ✓                                        | ✓ (tested on x86_64 emulator too) |



Also tested (compilation + running) on macOS without any problems.

```
$ sw_vers && xcodebuild -version
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
Xcode 8.3.2
Build version 8E2002
```

**Comment by dyjakan** [comment]
Everything works out of the box on **macOS El Capitan 10.11.6** (compiled and run 10k iterations on [MuPDF](https://mupdf.com/), no crashes though 😭).

```
$ sw_vers && xcodebuild -version
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1510
Xcode 8.0
Build version 8A218a
```

Ubuntu x86-64 is already tested so no point re-testing. ✌️

**Comment by robertswiecki** [comment]
Awesome, thanks for testing and pull requests. I'll update the status.

I've also made it compilable under Cygwin in https://github.com/google/honggfuzz/commit/43bdac5983331713fff724f2460248cf62e05167

**Comment by robertswiecki** [comment]
And here it is :) - https://github.com/google/honggfuzz/releases

Thanks for help with updates and testing - now it's buildable/workable under most of common OS/archs
