### ISSUE TITLE
linux_kernel_ip: generating input

### ISSUE THREAD

**Issue by block8437** [google/honggfuzz#146]
Hi,

I was playing around with the linux_kernel_ip fuzzer example, and I was wondering how inputs could be generated.

**Comment by robertswiecki** [comment]
So... this is the craziest example out there :)

I generated inputs by connecting to the lo interface inside the namespace (entered via nsenter) and then dumped them with tcpdump and reconstructed to binary with perl.

I can share my corpus, if you'd like.

But, in order to make all of that work well, you'll need to change the kernel slightly - I made it to always set TCP ack number to 0x41414141 - as otherwise kernel would chose it at random. With that the fuzzer can establish TCP connections.

**Comment by block8437** [comment]
If you would share the corpus I'd really appreciate it!

**Comment by robertswiecki** [comment]
Here it is: https://drive.google.com/open?id=0B86hdL7CeBvARndjcTJDQ3lDOU0

It also includes my csum.patch for kernel (version 4.11 IIRC, or maybe  kernel-4.10.fc27 from Fedora) which sets TCP's ack to 0x41414141 and disables checksum checks in TCP and in UDP.

The command I used was

```
~/src/honggfuzz/honggfuzz --linux_perf_bts_block -f IN/ -P -n2 -F 66000 --linux_perf_kernel_only -w ./wordlist -- ./tun
```

What is problematic is that Intel BTS will return frequently jump branch from sysret_irq to random places in userland. It's just an effect of context switching. I generally tried to identify this address (by printing new BTS jump pairs) and then blocked it in

```
linux/perf.c
```
with

```
    ......
    for (; br < ((struct bts_branch *)(fuzzer->linux.perfMmapAux + aux_head)); br++) {
       /* Addresses around sysret_irq */
        if (br->from == 0xffffffffa8985697) {
            continue;
        }
        if (br->from == 0xffffffffa898567b) {
            continue;
        }
       .....
```

Hope this helps!

**Comment by block8437** [comment]
Thank you so much for your help and your work on this project!
