### ISSUE TITLE
Android 'libUnwind' out of date, patches no longer required

### ISSUE THREAD

**Issue by zachriggle** [google/honggfuzz#161]
The upstream `libUnwind` provided by Google now has the changes specified in the patches, which means the submodule should be updated.

**Comment by robertswiecki** [comment]
sure, happy to merge PRs :), please CC @anestisb on Android-related changes as 99% of code is his :)

**Comment by anestisb** [comment]
It is in my todo list for quite some [time](https://github.com/google/honggfuzz/issues/139#issuecomment-302336583). It just needs a lot of porting work due to the different build systems & deps handling implemented in AOSP. Some changes made in AOSP repo to be compatible with the custom build system were never back-ported to the autoreconf/configure files.

Another plan is to include precompiled static libs matching each API level build from the AOSP infra, but I personally don't like that approach (who likes more binaries in git anyway).

So ideally I'm aiming to do this porting work soon and allow building from AOSP repo without requiring to maintain the libunwind patches. Extra hands are more than welcome of course.

**Comment by zachriggle** [comment]
One of my goals is also to get Honggfuzz to build from within an AOSP checkout, for the target `lunch`ed device.

**Comment by anestisb** [comment]
@zachriggle just noticed that you've pushed honggfuzz in AOSP made available from Android 9 branch. Cheers for that. The current build config is using the AOSP's libunwind which is heavily modified from the Android team. Did a dry run for an aarch64 sample badcode and the unwinder seems to have some issues (see following snippet). Haven't checked yet the coverage engines (will do the following days). bionic compatibility seems to also have some issues. Haven't checks yet the sanitizer coverage, verifier & blacklist functions.

I'm in the process of upgrading my Android fuzzing infrastructure to Android 9 and want to grab this opportunity to improve the Android support. Personally I really like the AOSP module option since I do most of my fuzzing in Pixel/Nexus devices. However, I'm guessing that @robertswiecki still wants to maintain standalone Android support via NDK.

Now the tricky situation regarding libunwind (which I believe is the first priority) is that the AOSP repo needs some additional work in order to be compiled with NDK. And the AOSP honggfuzz codebase needs some additional work to operate with the AOSP libunwind.

Are you planning to individually track the AOSP related changes in the AOSP fork or merge them here (e.g. detect build system for Android)? Also do you have any scheduled plans for the Android support you want to share (just want to ensure that we don't steer towards different approaches)?

Hopefully will get the libunwind resolved the next couple of weeks, cleanup some legacy code/function and start working on an ARM CoreSight feedback module for recent devices (e.g. Pixel 2).

```
walleye:/data/local/tmp $ file badcode
badcode: ELF shared object, 64-bit LSB arm64, dynamic (/system/bin/linker64), for Android 24, built by NDK r17b (4828580), BuildID=20346be2383706cb1f888c413e554c8b8643c27a, not stripped

walleye:/data/local/tmp $ ./hf -f corpus -N 1000 -v -- /data/local/tmp/badcode ___FILE___
PID: 2590, inputDir 'corpus', nullifyStdio: true, fuzzStdin: false, saveUnique: true, mutationsPerRun: 6, externalCommand: 'NULL', runEndTime: 0 tmOut: 10, mutationsMax: 1000, threads.threadsMax: 4, fileExtn: 'fuzz', ASLimit: 0x0(MiB), RSSLimit: 0x0, DATALimit: 0x0, fuzzExe: '/data/local/tmp/badcode', fuzzedPid: 0, monitorSIGABRT: 'false'
[2018-09-04T16:46:29+0300][W][2590] arch_archInit():396 Unknown libc implementation. Using clone() instead of fork()
[2018-09-04T16:46:29+0300][W][2590] files_readFileToBufMax():50 Couldn't open '/sys/bus/event_source/devices/intel_pt/type' for R/O: No such file or directory
[2018-09-04T16:46:29+0300][W][2590] files_readFileToBufMax():50 Couldn't open '/sys/bus/event_source/devices/intel_bts/type' for R/O: No such file or directory
Entering phase 1/2: Dry Run
Launched new fuzzing thread, no. #0
Launched new fuzzing thread, no. #1
Launched new fuzzing thread, no. #2
Launched new fuzzing thread, no. #3
Ok, that's interesting, saved './honggfuzz.input.0.badcode.fuzz' as './SIGSEGV.PC.7fb7c5dc9c.STACK.866be276.CODE.1.ADDR.0x8000000000.INSTR.ldp_x12,_x13,_[x1,_#0x40]!.fuzz'
Entering phase 2/2: Main
[2018-09-04T16:46:30+0300][F][2593] fuzz_prepareFileDynamically():103 The dynamic file corpus is empty. Apparently, the initial fuzzing of the provided file corpus (-f) has not produced any follow-up files with positive coverage and/or CPU counters

walleye:/data/local/tmp $ cat HONGGFUZZ.REPORT.TXT
=====================================================================
TIME: 2018-09-04.16:46:30
=====================================================================
FUZZER ARGS:
 mutationsPerRun : 6
 externalCmd     : NULL
 fuzzStdin       : FALSE
 timeout         : 10 (sec)
 ignoreAddr      : 0x0
 ASLimit         : 0 (MiB)
 RSSLimit        : 0 (MiB)
 DATALimit       : 0 (MiB)
 targetPid       : 0
 targetCmd       :
 wordlistFile    : NULL
 dynFileMethod:
 fuzzTarget   : /data/local/tmp/badcode ___FILE___
ORIG_FNAME: sample1
FUZZ_FNAME: ./SIGSEGV.PC.7fb7c5dc9c.STACK.866be276.CODE.1.ADDR.0x8000000000.INSTR.ldp_x12,_x13,_[x1,_#0x40]!.fuzz
PID: 2595
SIGNAL: SIGSEGV (11)
FAULT ADDRESS: 0x8000000000
INSTRUCTION: ldp_x12,_x13,_[x1,_#0x40]!
STACK HASH: 00000000866be276
STACK:
 <0x0000007fb7c5dc9c> [():0 at /system/lib64/libc.so]
 <0x0000005555555a10> [():0 at /data/local/tmp/badcode]
=====================================================================
```

**Comment by zachriggle** [comment]
The code that's checked in is part of the platform code, and as such *is
not *built by the NDK.  Why is there preference to build it with the NDK?

Separately, I don't expect that CoreSight tracing will work.  There's no
support for it, and I'm not sure that Qualcomm's SOCs implement it.

I'd recommend trying to bring it up on Pixel 3, rather than Pixel 2, since
it'll be supported longer.

**Comment by robertswiecki** [comment]
> @robertswiecki still wants to maintain standalone Android support via NDK.

Ekhem.. dunno :) I test whether it compiles with NDK sometimes, but I don't have opinion on which way to go besides that it should be usable to as many people as possible.

**Comment by zachriggle** [comment]
Thanks for the context @robertswiecki!

For clarity, I have no problem with **this** repo supporting the NDK (and it's likely necessary to fuzz things which are themselves built with the NDK), but the copy/fork in AOSP `external/hongfuzz` is not built / should not be built with the NDK, since it's intended for fuzzing the OS internals (which, similarly, are not built with the NDK).

**Comment by Tim-Nosco** [comment]
Trying to get `make android` working with the newest NDK, but first problem was the `compile-libunwind` script trying to call `gcc` which is no longer included in the NDK. I was trying to patch the script to use tripple-prefix clang binaries, but maybe this is not required if someone has better way.

**Comment by robertswiecki** [comment]
Updated the libunwind compilation. libunwind still needs some patches (missing context()) for arm64, but otherwise it works well. Also changed everything to clang.
