### ISSUE TITLE
hfuzz-clang: linker command failed

### ISSUE THREAD

**Issue by dobin** [google/honggfuzz#186]
When i try to compile with hfuzz-clang, i get the following error:
```
# honggfuzz/hfuzz_cc/hfuzz-clang helloworld.c 
[...]
/tmp/libhfuzz.0.3c162763de5970d9.a(instrument.o): In function `__sanitizer_cov_indir_call16':
instrument.c:(.text+0x4f0): multiple definition of `__sanitizer_cov_indir_call16'
/usr/lib/llvm-4.0/bin/../lib/clang/4.0.1/lib/linux/libclang_rt.ubsan_standalone-x86_64.a(sanitizer_coverage_libcdep.cc.o):(.text+0x4700): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried it on Ubuntu 17.04, and a brand new 17.10 lxd container: `apt-get install -y libbfd-dev libunwind-dev clang-4.0`

**Comment by robertswiecki** [comment]
Can you try with clang-5.0/llvm-5.0 ? __sanitizer_cov_indir_call16 is part of old clang-4 interface, and in llvm-4.0 for some strange reason is marked as a strong symbol instead of weak one.

I guess, for the sake of use, I can mark it as weak in honggfuzz, since it's an old interface anyway. Please try with https://github.com/google/honggfuzz/commit/51f6dae8f6344f22c0ed9569ae093e40c1179688

**Comment by dobin** [comment]
51f6dae indeed fixes the problem with clang-4, thanks. 

I have not tried it with clang-5. I used clang-4 because it was default in Ubuntu 17.04 (now EOL), where I had good experiences with honggfuzz.
