### ISSUE TITLE
HFUZZ-Clang not compatible with Clang5

### ISSUE THREAD

**Issue by x9090** [google/honggfuzz#187]
I encountered some compilation errors when using hfuzz-clang when enabling asan&masan (HFUZZ_USE_ASAN=1 HFUZZ_USE_MASAN=1) at the same time. Clang5 complaints that multiple "-fsanitize=" is not allowed. After fixing that, I realized that the llvm-compiled binary not able to generate coverage files. Besides that, the fuzzer hits SIGABRT consistently but in fact it's not caused by real crash.
  
So my gut feeling is that it could be some incompatibility issues with Clang5. I'm wondering also what is the best version of clang that you used  for testing/development?

**Comment by x9090** [comment]
I just learnt that honggfuzz is using in-process coverage feedback, so the debug message saying that "sancov map file not found" can be safely ignored.

Basically, "--sancov" option is not supported by clang >= 4.0 anymore as per my testing since *.sancov.raw and *.sancov.map will never be generated.

Please correct me if i'm wrong.

**Comment by robertswiecki** [comment]
Hi,

@anestisb might know more, but I think with clang-5.0 the sancov might not be working that well, as the coverage=1 envvar seems not to be working anymore (??). Maybe it has changed it name or sth.

With libFuzzer it works, because it can call ASAN API when -coverage=1 flag is passed to libFuzzer, but honggfuzz doesn't interact with ASAN API, except for envvars.

Except for rare cases we'll be using trace-pc-guard in the future, so if there's easy fix for that, we can apply it to honggfuzz, if not, it really depends on how much it is needed. I know @anestisb uses it with older Android versions, though I understand it's something of a legacy setup.

**Comment by x9090** [comment]
Thanks for the clarification, Robert!

**Comment by anestisb** [comment]
Upstream Android has added support for trace-pc-guard (and other in-process fuzzing opts) in its build backend (see build/core/config_sanitizers.mk) on the very recently released 8.1 version. So yes, it indeed makes sense to deprecate the old sancov map/raw file parsers & logic, so the related functions can be cleaned-up (see also https://github.com/google/honggfuzz/issues/168)

However, people fuzzing in versions <= 8.0 cannot benefit from the in-process fuzzing. It's up to @robertswiecki when he wants to flip the switch. Personally, I plan to migrate my infrastructure from 8.0 to 8.1 at some point soon. Until then I can keep working with an older tag if @robertswiecki wants to apply the changes immediately.

Also it might be a good idea to update the Android doc when the changes are applied so users can be aware that they have to use an older tag if they want to fuzz with sanitizers for < 8.1.
