### ISSUE TITLE
can't compile persistent code on OSX

### ISSUE THREAD

**Issue by iZsh** [google/honggfuzz#189]
Hello,

we can't compile persistent code on OSX due to the --wrap option which is not supported:
This fails with both hfuzz-gcc and hfuzz-clang

```
ld: unknown option: --wrap=strcmp
collect2: error: ld returned 1 exit status
```

**Comment by robertswiecki** [comment]
We can probably #ifdef wrap's for MacOS as these are not critical.

But, the biggest problem is lack of persistent code in mac/arch.c - so it will not work. You can try compiling with

OS=POSIX make clean all

and give it a try under MacOS. Otherwise "somebody" (TM) would have to replicate the persistent logic inside mac/arch.c - the relevant code from posix/arch.c starts around here: https://github.com/google/honggfuzz/blob/master/posix/arch.c#L195

**Comment by robertswiecki** [comment]
I've surrounded --wrap by if-not-macosx define. These --wrap's are not critical. Thugh, still, persistent code is not in mac/arch.c - it's not very complex imo, just returning from a loop if a iteration sign has been received over socket, but given that I don't have access to MacOSX box now, I cannot implement it myself.

**Comment by robertswiecki** [comment]
I thimk this is fixed at HEAD. Please re-open if needed.
