### ISSUE TITLE
Using honggfuzz to recover broken JPEG images?

### ISSUE THREAD

**Issue by rr-** [google/honggfuzz#208]
Rather than finding unique crashes, I'd like to use the fuzzer to find a variation of the source image that djpeg can successfully decode without any errors. (They're huge photos from a damaged SD card.)

Is this even possible?

Thanks.

**Comment by robertswiecki** [comment]
Depending on your definition of 'recovery'.. honggfuzz will try to increase global code coverage, so at some point it might produce a valid JPEG from your input, but there are no guarantees that the actual image data will not be touched.

In order to do that you'd have to modify honggfuzz internal mutators to make them aware of JPEG format, so the actual image data is not manipulated. It's not easy, and also no guaranteed to work.

In any case, here's the persistent JPEG decoder code - https://github.com/google/honggfuzz/tree/master/examples/libjpeg - should be faster than running JPEG repeatedly.

1. Compile jpeg-9b with honggfuzz

```
$ CC=/home/jagger/src/honggfuzz/hfuzz_cc/hfuzz-clang ./configure && make
```

2. Compile persistent-jpeg

```
$ /home/jagger/src/honggfuzz/hfuzz_cc/hfuzz-clang /home/jagger/src/honggfuzz/examples/libjpeg/persistent-jpeg.c -I./jpeg-9b/ -o persistent.jpeg9 jpeg-9b/.libs/libjpeg.a
```

3. Run it on your corpus

```
$ /home/jagger/src/honggfuzz/honggfuzz -f IN -P -- ./persistent.jpeg9
```

4. Periodically check IN for whether it contains any valid JPEG.


The alternative would be to add ```abort()``` in persistent-jpeg.c so it SIGABRT's when a valid JPEG file was processed, should be included somewhere before the ```out:``` label I guess.

Good luck!

**Comment by rr-** [comment]
Thanks for the detailed approach - it seems to be working, although yeah, it does mutate the "untouchable" data. An option to use a static prefix of fixed size from the corpus would be great.
