### ISSUE TITLE
Any way to get sanitizer stacktraces for e.g. SIGSEGV? 

### ISSUE THREAD

**Issue by oliverchang** [google/honggfuzz#281]
ClusterFuzz relies on parsing sanitizer stacktraces to report signal failures like SEGV. It seems like honggfuzz doesn't output these in such cases (as opposed to e.g. a UaF). Would it be possible to get these?

(https://github.com/google/clusterfuzz/issues/1128)

**Comment by robertswiecki** [comment]
Hi, could you elaborate? Are maybe thinking about seeing output from asan/msan/tsan on the stderr?

**Comment by oliverchang** [comment]
Sorry for the confusion! Yes, we need to see the sanitizer stacks for these signals.

**Comment by robertswiecki** [comment]
Hi,

I've checked it, and I don't think it's possible. One can run honggfuzz with ```-Q``` to display output, but it'll obviously also show output from fuzzed processes' stdout/stderr. There's ASAN_OPTIONS flag which can be used to redirect reports, but it can be only set to "stdout"/"stderr", and everything else will be treated as a file prefix to save the log (this file will be actually created, with some PID value appended to it).

And what we need here (unless you want to parse some random files) is something like ASAN_OPTIONS=log_path=log_fd-1021 (because I use FD 1021 to logging, as in, early duplicated stderr).

CCing @kcc in case he might some other ideas, or in case he decides that logging to fd is a possible feature to implement in compiler-rt.

**Comment by oliverchang** [comment]
Thanks for investigating @robertswiecki !

I want to clarify that we are already getting ASan stacktraces for crashes like heap OOBs via HF.sanitizer.log*: https://github.com/google/honggfuzz/blob/ac7df4eddcbf10a870e94933e13405544550bac4/linux/trace.c#L847

However this only seems to get called in the case of exitcode errors, and don't seem to work properly for signal failures. Is there some easy way to make this work here?

**Comment by robertswiecki** [comment]
I'll work on that

**Comment by robertswiecki** [comment]
Hi oliver,

I gave it a though, and I'd like to get your opinion on the following.

So, honggfuzz is a multi-process fuzzer, which doesn't exit upon first crash. Therefore if we find a crash, getting ASan report for it is not easy because the only source of data linking crash to stack-traces and other metadata is the HONGGFUZZ.REPORT.TXT file.

Therefore I'd like to propose something different, which might simplify this conundrum. I propose running honggfuz (and e.g. AFL) for as long as possible (without the --exit_upon_crash flag), and at the end of sessions (e.g. after a couple of hours), to gather all crashes, and run them through the canonical source of truth (e.g. through libfuzzer), and getting stack-traces and other metadata directly from there. Then it'll require just single parser for asan.

That's what autofuzz does (did?), and that worked very well. The alternative is that you'd have to write very specific code for afl and for honggfuzz and for any other engines you might want to try here. And having a single confirmation engine (can be obviously libfuzzer) would simplify all of that.

WDYT?

Please let me know, if that's

**Comment by oliverchang** [comment]
Hey Robert,

We can potentially do something similar, where we run all the reproducers against the crashes generated by honggfuzz in a single session. We can't use another engine for confirmation, since we make no assumptions about the availability of builds at the same revision for another engine.

However, it would make our implementation a *lot* simpler if we could get the stacktraces as we are fuzzing. Right now it's easy to do so via --exit_upon_crash and looking for the sole HF.sanitizer.log* file. Perhaps there's not much benefit to running honggfuzz for as long as possible, because we run the same target+engine multiple times in quick succession in a single fuzzing session.

In any case, is this a different problem from not being able to get sanitizer stacktraces for signals?

**Comment by robertswiecki** [comment]
The problem for SIGSEGV and asan is that honggfuzz uses ptrace to actively look for signals being delivered to processes. If it sees SIGSEGV and if --exit_upon_crash is set, then it stops execution of a traced process, saves poc and data to HONGGFUZZ.REPORT.TXT and exits.

Asan intercepts SIGSEGV handler, and prints some data from within there. But intercepting the handler doesn't stop the signal from being delivered (and honggfuzz seeing it).

You could maybe compile honggfuzz with 

```shell
OS=POSIX make clean all
```

This will prevent ptrace() from being used, and honggfuzz will not see SIGSEGV when it's delivered, but only when the process exits. And, because we set ASAN_OPTIONS=abort_on_error=1 then it'll see SIGABRT.

If you only have libfuzzer style of fuzzers, then I guess this might work, as no additional processes are spawned which need monitoring. The posix version is much less complex, it doesn't use ptrace() or libdisassm or perf, but I guess you don't use that. Feel free to give it a try, maybe it'll work well, at least I don't see any reasons why it shouldn't.

**Comment by robertswiecki** [comment]
The additional benefit is that with 

```shell
OS=POSIX make
```

It'll not link unwind or disassm in. I don't use the posix version on a daily basis (it's used e.g. with FreeBSD), I think it should work if you only use asan and single processes, but please let me know if you see any hiccups.

All testcases will be saved then in a slightly different format, e.g. as ```SIGABRT.PID.775128.TIME.2019-11-29.08.28.08.fuzz```

**Comment by robertswiecki** [comment]
Or, please try now with ```-S```. With https://github.com/google/honggfuzz/commit/7a1d2d6e0f711cca95ab6166e1c7db60223c087f it should be possible to do what you want.

**Comment by robertswiecki** [comment]
I hope this works.. closing, please reopen if needed.

**Comment by oliverchang** [comment]
Sorry for the slow response, and thanks a ton for implementing this!

I'm out this week, but will try it out next week.
