### ISSUE TITLE
how to show current code coverage

### ISSUE THREAD

**Issue by LH-413x** [google/honggfuzz#283]
Hi,
Does honggfuzz support show code coverage like syzkaller?

**Comment by robertswiecki** [comment]
You can analyze the feedback map through /proc/<fuzzed_pid>/fd/1022, but it's a bit opaque. But if you're looking for a nice-and-easy solution (like colorifying some source code browser) then, nope, hongffuzz doesn't export such data in an easy way.

**Comment by marcellomaugeri** [comment]
@robertswiecki sorry for reopening the issue, but it seems that I cannot find the fd 1022. In that folder there are only 
`0   1   19  2   20  21  22  23  25  3   4  5   6   7   8   9   99`
maybe it is due to I am not using the persistent mode, then I cannot access <fuzzed_pid> but only the main process of Honggfuzz. If so, how can I access the cumulative coverage? Thank you
