### ISSUE TITLE
qemu_mode shared lib coverage

### ISSUE THREAD

**Issue by korniltsev** [google/honggfuzz#330]
If I understand correctly, right now it is possible to trace coverage in two ways
- only RX section of loaded elf
- all code with `HFUZZ_INST_LIBS`

It might be useful to be able to trace coverage of specific shared libs, especially if the vulnerable code is in a shared lib. Would be cool if we could  trace an arbitrary shared lib and ignore let's say `libc.so` for example with another env variable `HFUZZ_TRACE_RANGES=0x1234-0x5678` or some other way

Do you think this might be a useful feature?

**Comment by evanrichter** [comment]
I've had situations where this would be useful as well

**Comment by robertswiecki** [comment]
Yeah, this looks like a nice avenue for improving honggfuzz/honggfuzz-qemu.

Please note that this feature would most likely be implemented in the ```https://github.com/thebabush/honggfuzz-qemu``` codebase.

One could also go a bit further, and maybe use more human-readable format, like

HFUZZ_QEMU_INST=binary_only

or

HFUZZ_QEMU_INST=binary,lib:liba.so,lib:libb.so

in addition to numeric values.

**Comment by korniltsev** [comment]
I am happy to hear this idea makes sense. 
I already have a dirty prototype for a private fuzzer.  https://github.com/korniltsev/honggfuzz-qemu
I could clean it up and work on PR if this can be considered to merge. 
@thebabush What do you think?

**Comment by thebabush** [comment]
I'm not a huge fan of string manipulation/parsing in C :D but it looks good.
It you tested it and it works, I trust you.

The only pain point I see is that the patch introduces a loop for every tlb translation. Ideally we should code the trace logic in TCG but I can't justify it at the moment (maybe I could piggyback on aflplusplus' QEMU...) as that can cause problems with threading and so it needs some effort.

This leads me to another thing: my patch of qemu is bugged. Currently, I don't disable translation block chaining (`QEMU_LOG=nochain`). This means that the coverage callback is called only at translation time. However I think by pure chance we are fine since we don't cache TB across fork (or maybe I thought about it and this behavior is intended... don't remember. I'll document it somewhere just to be sure).

Sorry for the stream of consciousness. My only objection to a PR is that it could have a performance penalty. I think it should be negligible compared to, eg, chaining TBs, but can you do some quick test pre/post commit? Ofc with `hfuzz_qemu_img_cnt = 1`. Nothing fancy, just take your go-to not-too-small fuzzing target and see if you see any significant difference in exec/s.
Otherwise open the PR and when I have time to run some tests I can confirm it myself and merge it (I'm not working on fuzzing these days).

**Comment by robertswiecki** [comment]
Spring cleaning, please re-open if needed
