### ISSUE TITLE
`-llzma` linked in, but not used

### ISSUE THREAD

**Issue by rwmjones** [google/honggfuzz#332]
In `Makefile` you link with `-llzma`, but as far as I can see you're not using lzma anywhere, and the program appears to function fine without it.

Discovered during Fedora package review: https://bugzilla.redhat.com/show_bug.cgi?id=1834964#c7

**Comment by robertswiecki** [comment]
Hi,

the story about this is here https://github.com/google/honggfuzz/pull/307

But in short, DT_NEEDED sections of used linunwind libraries seem a bit incorrect in Ubuntu (also when using pkg-config --libs), and it creates some problems under some linkers, namely lld, which seems to more strictly observe order of needed libraries.

I didn't find a better way of fixing this problem, and this probably needs to be fixed on the libunwind level (or in their pkg-config config files). If you this doesn't cause problem in Fedora, feel free to patch it out in the Makefile, but since there are Ubuntu users which prefer ld.lld I don't think there will be an easy solution to that.

Though, my analysis of the problem was superficial at best, if you feel like diving into it, and proposing some solution which works under Ubuntu/lld and with other Linux distros, and doesn't use such hacks, I'll be happy to implement it.

**Comment by rwmjones** [comment]
That's fine.  You can close this bug if you want.  Our process requires that I have a bug / link I can point to in the spec file, and now I have one.

FWIW honggfuzz will go into Fedora shortly.

**Comment by robertswiecki** [comment]
Good news, thank you!
