### ISSUE TITLE
How to identify whether the current fuzzing has finished?

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#77]
How to identify whether the current fuzzing with honggfuzz has finished?

**Comment by robertswiecki** [comment]
The honggfuzz process just ends.... or maybe you're thinking of some other definition of "honggfuzz has finished"?

**Comment by riusksk** [comment]
Do you mean that honggfuzz process will ends when the fuzzing work of all the variant files was finished ?

**Comment by robertswiecki** [comment]
You can impose limit on number of iterations (-N). There's no really other stop condition in honggfuzz. If you want to test every individual file, you can run honggfuzz on each of them with "-N 1".

for x in *; do honggfuzz -N1 -f "$x" -- ./test ___FILE___; done

**Comment by riusksk** [comment]
thx, can u add the percentage of current fuzzing processing like AFL "now processing: 34%"?

**Comment by robertswiecki** [comment]
I've added in https://github.com/google/honggfuzz/commit/4eab0b5e65268b5e1573c8c4ec1d7024a6fdd9c6 a more detailed display of progress.

But it works only if you specify -N <number>. Otherwise we don't have any "progress" indicator (modulo the coverage from sancov module).

Iterations: 16750 (out of: 10000000 [0.17%])

**Comment by riusksk** [comment]
厉害啊！thx
